[tools]
bat = "latest"
erlang = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
java = "17"
jq = "latest"
node = "22"
opencode = "latest"
pnpm = "latest"
python = "3.13"
ripgrep = "latest"
ruby = "latest"
starship = "latest"
uv = "latest"
yazi = "latest"
