alias l='nls -l'
alias v='nvim'
alias c='clear'
alias astro='NVIM_APPNAME=astro nvim'
alias gs='git status'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ld='lazydocker'
alias lg='lazygit'
