ZINIT_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git"

if [[ ! -d "$ZINIT_HOME" ]]; then
    mkdir -p "$(dirname "$ZINIT_HOME")"
    git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

source "$ZINIT_HOME/zinit.zsh"




source ~/.config/zsh/keybind.zsh
source ~/.config/zsh/tools.zsh
source ~/.config/zsh/completion.zsh
source ~/.config/zsh/alias.zsh
source ~/.config/zsh/history.zsh
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/snippets.zsh
source ~/.config/zsh/env.zsh
