config-version = 2
start-at-login = true

after-startup-command = [
    'exec-and-forget open -a Kitty',
    'exec-and-forget open -a "Firefox Developer Edition"',
]

[mode.main.binding]

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 0'

alt-e = 'workspace E'
alt-r = 'workspace R'
alt-u = 'workspace U'
alt-i = 'workspace I'
alt-o = 'workspace O'
alt-p = 'workspace P'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 0'

alt-shift-w = 'move-node-to-workspace W'
alt-shift-u = 'move-node-to-workspace U'
alt-shift-i = 'move-node-to-workspace I'
alt-shift-o = 'move-node-to-workspace O'
alt-shift-p = 'move-node-to-workspace P'

alt-h = 'workspace --wrap-around prev'
alt-l = 'workspace --wrap-around next'

alt-tab = 'workspace-back-and-forth'

alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-h = 'move-node-to-workspace --wrap-around prev'
alt-shift-l = 'move-node-to-workspace --wrap-around next'

alt-comma = 'resize smart -50'
alt-period = 'resize smart +50'

alt-f = 'fullscreen'
alt-shift-f = 'macos-native-fullscreen'

alt-t = 'layout floating tiling'
alt-s = 'layout tiles horizontal vertical'

alt-enter = 'exec-and-forget open -n /Applications/Kitty.app'

alt-shift-q = 'close'
alt-shift-r = 'reload-config'
alt-shift-e = 'close-all-windows-but-current'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'org.mozilla.firefoxdeveloperedition'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'dev.zed.Zed'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.google.antigravity'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'dev.kdrag0n.MacVirt'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.vivaldi.Vivaldi'
run = 'move-node-to-workspace P'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 0'
