###########
# History #
###########

HISTSIZE=100000
HISTFILESIZE=200000
HISTCONTROL=ignoreboth:erasedups
HISTIGNORE="ls:cd:pwd:exit:clear"
shopt -s histappend checkwinsize

###############
# Environment #
###############

export EDITOR=nvim
export VISUAL=nvim

export PYENV_ROOT="$HOME/.pyenv"
export PYENV_REHASH_DISABLE=1

export DATABASE_NAME=testpress
export DATABASE_USER=testpress
export DATABASE_USER_PASSWORD='testpress1$'

export ANDROID_HOME="$HOME/Library/Android/sdk"

############
# PATH
############

export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$PYENV_ROOT/bin:$PATH"

path_add() {
    [[ -d "$1" && ":$PATH:" != *":$1:"* ]] && PATH="$1:$PATH"
}

path_add "$HOME/.antigravity/antigravity/bin"
path_add "$HOME/.antigravity-ide/antigravity-ide/bin"
path_add "$ANDROID_HOME/platform-tools"
path_add "$ANDROID_HOME/emulator"
path_add "$ANDROID_HOME/cmdline-tools/latest/bin"

###############
# Completions #
###############

[[ -f /opt/homebrew/etc/profile.d/bash_completion.sh ]] &&
source /opt/homebrew/etc/profile.d/bash_completion.sh

###########
# Tooling #
###########

command -v mise >/dev/null &&
eval "$(mise activate bash)"

command -v starship >/dev/null &&
eval "$(starship init bash)"

command -v zoxide >/dev/null &&
eval "$(zoxide init bash)"

command -v atuin >/dev/null &&
eval "$(atuin init bash)"

command -v pyenv >/dev/null &&
eval "$(pyenv init -)"

command -v rbenv >/dev/null &&
eval "$(rbenv init -)"

[[ -f ~/.fzf.bash ]] &&
source ~/.fzf.bash

[[ -f ~/.local/share/blesh/ble.sh ]] &&
source ~/.local/share/blesh/ble.sh

####################
# Load user config #
####################

[[ -f ~/.bash_aliases ]] &&
source ~/.bash_aliases

[[ -f ~/.bash_functions ]] &&
source ~/.bash_functions

[[ -f ~/.config/bash/secrets.sh ]] &&
source ~/.config/bash/secrets.sh

ble-bind -m emacs -f RET accept-line
ble-bind -m emacs -f C-m accept-line
export PATH="/Users/bala/.opencode/bin:$PATH"
